# Generated by Django 4.2.30 on 2026-06-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Numero')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicacion')),
                ('status', models.CharField(choices=[('free', 'Libre'), ('occupied', 'Ocupada'), ('reserved', 'Reservada'), ('cleaning', 'Limpieza')], default='free', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
    ]
