# Generated by Django 6.0.3 on 2026-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
    ]
